spring:
  database:
    datasource:
      url: jdbc:postgresql://localhost:5432/bankingapp-account-service
      username: postgres
      password: postgres

  kafka:
    bootstrap-servers: localhost:9092

    jpa:
      hibernate:
        ddl-auto: update
        show-sql: true
        format_sql: true
  h2:
    console:
    enabled: true

bankingapp:
  kafka:
    topic:
      transfer-valid: transfer-valid
      transfer-failed-status: transfer-failed-status



server:
  port: 8091

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: "*"